version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_RUN_PORT: 5001

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
