name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to version 3 for Node.js 20 support

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4  # Updated to version 0.8.1 for Node.js 20 support
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@209.38.174.80 'bash /opt/tide-calendar/deploy.sh'
